# Generated by Django 4.2.6 on 2024-11-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='meal_name',
        ),
    ]
