# Generated by Django 4.2.6 on 2024-02-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_mealentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(to='common.ingredient'),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='common.ingredient'),
        ),
    ]
